excluded:
  - Pods
  - Carthage
  - ./R.generated.swift
  - SubCreatorTests
  - SubCreatorUITests
  - ./SubCreator/Utility/Device
  - ./SubCreator/iOS/Controllers/Photo
disabled_rules:
  - trailing_whitespace

disabled_rules:
  - identifier_name
  - trailing_whitespace
  - cyclomatic_complexity
  - unused_closure_parameter
  - notification_center_detachment
  - for_where
  - empty_count
  - multiple_closures_with_trailing_closure

control_statement:
  severity: error

force_unwrapping:
  severity: error

force_cast:
  severity: error

force_try:
  severity: error

line_length:
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true
  warning: 199
  error: 200

function_parameter_count:
  warning: 5
  error: 7

function_body_length:
  warning: 300
  error: 400

type_body_length:
  warning: 400
  error: 500

file_length:
  warning: 999
  error: 1000

custom_rules:
  uiimage_with_name:
    name: "UIImage With Name"
    regex: '(UIImage\(named:.*\))'
    message: "Use R.image replace UIImage(named:)."
    severity: warning

reporter: "xcode"